# Generated by Django 2.0.1 on 2018-02-21 20:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_announcement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='display_start',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
