# Generated by Django 2.0.1 on 2018-03-09 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20180221_1246'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pennant',
            fields=[
                ('district', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='website.PennantDistrict')),
                ('next_game', models.DateField()),
            ],
        ),
        migrations.RenameField(
            model_name='venue',
            old_name='pennant',
            new_name='has_pennant',
        ),
    ]
