# Generated by Django 2.0.1 on 2018-03-16 00:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20180309_0004'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hold',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(default=datetime.datetime.now)),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('message', models.CharField(blank=True, max_length=100, null=True)),
                ('venue', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='website.Venue')),
            ],
        ),
    ]
