# Generated by Django 2.0.1 on 2018-03-16 06:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_hold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hold',
            name='end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hold',
            name='start',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
