# Generated by Django 2.0.1 on 2018-03-16 06:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_auto_20180315_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hold',
            name='start',
            field=models.DateField(default=datetime.date(2018, 3, 15)),
        ),
    ]
