# Generated by Django 2.0.1 on 2018-03-16 06:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_auto_20180315_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hold',
            name='start',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
