# Generated by Django 2.0.1 on 2018-03-16 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_auto_20180315_2331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='active',
        ),
    ]
