# Generated by Django 2.0.1 on 2018-02-21 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('website', '0004_auto_20180220_0046'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='checkin',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='palooza.Player'),
        ),
        migrations.AddField(
            model_name='checkin',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='website.Venue'),
        ),
    ]
