# Generated by Django 2.0.1 on 2018-02-21 07:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('palooza', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='date_added',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
